-- Migration: Update billing tables to support multiple payment providers
-- This migration adds support for Lemon Squeezy and Flutterwave alongside legacy Stripe

-- Create generic payment_customers table
CREATE TABLE IF NOT EXISTS public.payment_customers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('stripe', 'lemon-squeezy', 'flutterwave')),
  payment_customer_id TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_payment_customers_user_id ON public.payment_customers(user_id);
CREATE INDEX idx_payment_customers_provider ON public.payment_customers(provider);

-- Create generic payment_subscriptions table
CREATE TABLE IF NOT EXISTS public.payment_subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subscription_id TEXT NOT NULL,
  provider TEXT NOT NULL CHECK (provider IN ('stripe', 'lemon-squeezy', 'flutterwave')),
  plan TEXT NOT NULL CHECK (plan IN ('free', 'pro', 'agency')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'canceled', 'past_due', 'trialing')),
  renews_at TIMESTAMP WITH TIME ZONE,
  cancel_at_period_end BOOLEAN DEFAULT FALSE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(subscription_id, provider)
);

CREATE INDEX idx_payment_subscriptions_user_id ON public.payment_subscriptions(user_id);
CREATE INDEX idx_payment_subscriptions_provider ON public.payment_subscriptions(provider);
CREATE INDEX idx_payment_subscriptions_status ON public.payment_subscriptions(status);

-- Create payment_sessions table to track checkout sessions
CREATE TABLE IF NOT EXISTS public.payment_sessions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('stripe', 'lemon-squeezy', 'flutterwave')),
  session_id TEXT NOT NULL UNIQUE,
  plan_type TEXT,
  credits INTEGER,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'expired', 'failed')),
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_payment_sessions_user_id ON public.payment_sessions(user_id);
CREATE INDEX idx_payment_sessions_provider ON public.payment_sessions(provider);

-- Update credit_purchases table to include provider field
ALTER TABLE IF EXISTS public.credit_purchases 
ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'stripe',
ADD COLUMN IF NOT EXISTS payment_intent_id TEXT;

-- Create pending_credit_purchases table for tracking pending Flutterwave transactions
CREATE TABLE IF NOT EXISTS public.pending_credit_purchases (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  credits_pending INTEGER NOT NULL,
  tx_ref TEXT NOT NULL UNIQUE,
  provider TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_pending_credit_purchases_user_id ON public.pending_credit_purchases(user_id);

-- Enable RLS on new tables
ALTER TABLE public.payment_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pending_credit_purchases ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
DROP POLICY IF EXISTS "Users can view own payment customers" ON public.payment_customers;
CREATE POLICY "Users can view own payment customers" ON public.payment_customers
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own payment subscriptions" ON public.payment_subscriptions;
CREATE POLICY "Users can view own payment subscriptions" ON public.payment_subscriptions
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own payment sessions" ON public.payment_sessions;
CREATE POLICY "Users can view own payment sessions" ON public.payment_sessions
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own pending purchases" ON public.pending_credit_purchases;
CREATE POLICY "Users can view own pending purchases" ON public.pending_credit_purchases
  FOR SELECT USING (auth.uid() = user_id);

-- Create update triggers for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_payment_customers_updated_at ON public.payment_customers;
CREATE TRIGGER update_payment_customers_updated_at
  BEFORE UPDATE ON public.payment_customers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_payment_subscriptions_updated_at ON public.payment_subscriptions;
CREATE TRIGGER update_payment_subscriptions_updated_at
  BEFORE UPDATE ON public.payment_subscriptions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_payment_sessions_updated_at ON public.payment_sessions;
CREATE TRIGGER update_payment_sessions_updated_at
  BEFORE UPDATE ON public.payment_sessions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_pending_credit_purchases_updated_at ON public.pending_credit_purchases;
CREATE TRIGGER update_pending_credit_purchases_updated_at
  BEFORE UPDATE ON public.pending_credit_purchases
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
