-- ======================================================
-- PAYMENT PROVIDERS (Paddle / Flutterwave / Stripe optional)
-- SAFE + IDEMPOTENT VERSION
-- ======================================================

-- Ensure updated_at trigger exists
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ======================================================
-- PAYMENT CUSTOMERS
-- ======================================================

CREATE TABLE IF NOT EXISTS public.payment_customers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  payment_customer_id TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure missing columns exist
ALTER TABLE public.payment_customers
ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'flutterwave',
ADD COLUMN IF NOT EXISTS payment_customer_id TEXT,
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- Add constraint safely
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'payment_customers_provider_check'
  ) THEN
    ALTER TABLE public.payment_customers
    ADD CONSTRAINT payment_customers_provider_check
    CHECK (provider IN ('stripe', 'paddle', 'flutterwave'));
  END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_payment_customers_user_id 
ON public.payment_customers(user_id);

CREATE INDEX IF NOT EXISTS idx_payment_customers_provider 
ON public.payment_customers(provider);

-- Trigger
DROP TRIGGER IF EXISTS update_payment_customers_updated_at ON public.payment_customers;
CREATE TRIGGER update_payment_customers_updated_at
BEFORE UPDATE ON public.payment_customers
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ======================================================
-- PAYMENT SUBSCRIPTIONS
-- ======================================================

CREATE TABLE IF NOT EXISTS public.payment_subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  subscription_id TEXT,
  plan TEXT,
  status TEXT DEFAULT 'active',
  renews_at TIMESTAMPTZ,
  cancel_at_period_end BOOLEAN DEFAULT FALSE,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure columns exist
ALTER TABLE public.payment_subscriptions
ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'flutterwave',
ADD COLUMN IF NOT EXISTS subscription_id TEXT,
ADD COLUMN IF NOT EXISTS plan TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- Constraints
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'payment_subscriptions_provider_check'
  ) THEN
    ALTER TABLE public.payment_subscriptions
    ADD CONSTRAINT payment_subscriptions_provider_check
    CHECK (provider IN ('stripe', 'paddle', 'flutterwave'));
  END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_payment_subscriptions_user_id 
ON public.payment_subscriptions(user_id);

CREATE INDEX IF NOT EXISTS idx_payment_subscriptions_provider 
ON public.payment_subscriptions(provider);

CREATE INDEX IF NOT EXISTS idx_payment_subscriptions_status 
ON public.payment_subscriptions(status);

-- Trigger
DROP TRIGGER IF EXISTS update_payment_subscriptions_updated_at ON public.payment_subscriptions;
CREATE TRIGGER update_payment_subscriptions_updated_at
BEFORE UPDATE ON public.payment_subscriptions
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ======================================================
-- PAYMENT SESSIONS
-- ======================================================

CREATE TABLE IF NOT EXISTS public.payment_sessions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id TEXT UNIQUE,
  plan_type TEXT,
  credits INTEGER,
  status TEXT DEFAULT 'pending',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure columns
ALTER TABLE public.payment_sessions
ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'flutterwave',
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- Constraints
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'payment_sessions_provider_check'
  ) THEN
    ALTER TABLE public.payment_sessions
    ADD CONSTRAINT payment_sessions_provider_check
    CHECK (provider IN ('stripe', 'paddle', 'flutterwave'));
  END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_payment_sessions_user_id 
ON public.payment_sessions(user_id);

CREATE INDEX IF NOT EXISTS idx_payment_sessions_provider 
ON public.payment_sessions(provider);

-- Trigger
DROP TRIGGER IF EXISTS update_payment_sessions_updated_at ON public.payment_sessions;
CREATE TRIGGER update_payment_sessions_updated_at
BEFORE UPDATE ON public.payment_sessions
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ======================================================
-- CREDIT PURCHASES UPDATE
-- ======================================================

ALTER TABLE public.credit_purchases
ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'flutterwave',
ADD COLUMN IF NOT EXISTS payment_intent_id TEXT;

-- ======================================================
-- PENDING PURCHASES (Flutterwave use-case)
-- ======================================================

CREATE TABLE IF NOT EXISTS public.pending_credit_purchases (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  credits_pending INTEGER NOT NULL,
  tx_ref TEXT UNIQUE,
  provider TEXT,
  status TEXT DEFAULT 'pending',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure columns
ALTER TABLE public.pending_credit_purchases
ADD COLUMN IF NOT EXISTS provider TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';

-- Index
CREATE INDEX IF NOT EXISTS idx_pending_credit_purchases_user_id 
ON public.pending_credit_purchases(user_id);

-- Trigger
DROP TRIGGER IF EXISTS update_pending_credit_purchases_updated_at ON public.pending_credit_purchases;
CREATE TRIGGER update_pending_credit_purchases_updated_at
BEFORE UPDATE ON public.pending_credit_purchases
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ======================================================
-- RLS
-- ======================================================

ALTER TABLE public.payment_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pending_credit_purchases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own payment customers" ON public.payment_customers;
CREATE POLICY "Users can view own payment customers"
ON public.payment_customers
FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own payment subscriptions" ON public.payment_subscriptions;
CREATE POLICY "Users can view own payment subscriptions"
ON public.payment_subscriptions
FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own payment sessions" ON public.payment_sessions;
CREATE POLICY "Users can view own payment sessions"
ON public.payment_sessions
FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own pending purchases" ON public.pending_credit_purchases;
CREATE POLICY "Users can view own pending purchases"
ON public.pending_credit_purchases
FOR SELECT USING (auth.uid() = user_id);