-- Create webhook_logs table for monitoring webhook events
CREATE TABLE IF NOT EXISTS public.webhook_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  provider TEXT NOT NULL,
  event_type TEXT NOT NULL,
  user_id UUID,
  payload JSONB NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('success', 'failure')),
  error_message TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add missing columns to existing webhook_logs table from migration 007
ALTER TABLE public.webhook_logs
  ADD COLUMN IF NOT EXISTS provider TEXT,
  ADD COLUMN IF NOT EXISTS user_id UUID,
  ADD COLUMN IF NOT EXISTS status TEXT CHECK (status IN ('success', 'failure')),
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_webhook_logs_provider
  ON public.webhook_logs(provider);

CREATE INDEX IF NOT EXISTS idx_webhook_logs_event_type
  ON public.webhook_logs(event_type);

CREATE INDEX IF NOT EXISTS idx_webhook_logs_status
  ON public.webhook_logs(status);

CREATE INDEX IF NOT EXISTS idx_webhook_logs_created_at
  ON public.webhook_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_webhook_logs_user_id
  ON public.webhook_logs(user_id);

-- Create composite index for common queries
CREATE INDEX IF NOT EXISTS idx_webhook_logs_provider_status
  ON public.webhook_logs(provider, status);

-- Enable RLS (Row Level Security)
ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Admin can view all logs
CREATE POLICY "admins_can_view_webhook_logs"
  ON public.webhook_logs FOR SELECT
  USING (
    auth.jwt() ->> 'role' = 'authenticated' AND
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND plan = 'agency'
    )
  );

-- Users can view their own logs (optional)
CREATE POLICY "users_can_view_own_webhook_logs"
  ON public.webhook_logs FOR SELECT
  USING (
    auth.uid() = user_id
  );

-- Service role can manage all logs
CREATE POLICY "service_role_can_manage_webhook_logs"
  ON public.webhook_logs
  USING (auth.jwt() ->> 'role' = 'service_role');

-- Create function to update updated_at
CREATE OR REPLACE FUNCTION public.update_webhook_logs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
CREATE TRIGGER trigger_webhook_logs_updated_at
  BEFORE UPDATE ON public.webhook_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.update_webhook_logs_updated_at();

-- Create a view for webhook statistics
-- FIX: make the view SECURITY INVOKER so it respects the querying user's RLS
CREATE OR REPLACE VIEW public.webhook_stats_24h
WITH (security_invoker = on)
AS
SELECT
  provider,
  status,
  event_type,
  COUNT(*) as count,
  COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '1 hour') as count_last_hour,
  COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '6 hours') as count_last_6h
FROM public.webhook_logs
WHERE created_at > NOW() - INTERVAL '24 hours'
GROUP BY provider, status, event_type;

-- Grant permissions
GRANT SELECT ON public.webhook_logs TO authenticated;
GRANT SELECT ON public.webhook_stats_24h TO authenticated;